---
- name: create unifi-poller config
  template:
    src: up.conf.j2
    dest: "{{ unifi_exporter_config_dir }}/{{ unifi_exporter_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart unifi-poller
