---
- name: download binary to local folder
  get_url:
    url: "https://raw.githubusercontent.com/unifi-poller/unifi-poller/master/scripts/install.sh"
    dest: "/tmp/unifi-poller-install.sh"
  environment: "{{proxy_env}}"
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: run unifi-poller installation script
  script:
    cmd: /tmp/unifi-poller-install.sh
