---
- name: install selinux dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ unifi_exporter_selinux_packages }}"
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"

- name: allow binding to port in selinux
  seport:
    ports: "{{ unifi_exporter_web_listen_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
